version: "3"
services:
  app_user:
    build: ./app
    image: users:latest
    restart: always
    command: gunicorn -b 0.0.0.0:8080 -w 6 assignment1:app
    environment:
        TEAM_NAME: CC_0226_0298_0956_1554
    ports:
      - "80:8080"